version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:17.6-alpine
    container_name: financial-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - financial-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for Task Queue
  redis:
    image: redis:7-alpine
    container_name: financial-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - financial-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # SMTP Service (MailDev)
  smtp:
    image: maildev/maildev:latest
    container_name: financial-smtp
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP
    environment:
      - MAILDEV_DOMAIN=localhost
      - MAILDEV_SMTP=1025
      - MAILDEV_WEB=1080
    networks:
      - financial-network
    restart: unless-stopped

  # Prometheus for Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: financial-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - financial-network
    restart: unless-stopped

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: financial-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - financial-network
    restart: unless-stopped

  # Simple API Service
  api:
    image: python:3.11-slim
    container_name: financial-api
    working_dir: /app
    volumes:
      - ./simple-apps:/app
    command: >
      sh -c "
        pip install fastapi uvicorn python-dotenv psycopg2-binary redis &&
        python api.py
      "
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis
    networks:
      - financial-network
    restart: unless-stopped

  # Simple Frontend Service
  ui:
    image: python:3.11-slim
    container_name: financial-ui
    working_dir: /app
    volumes:
      - ./simple-apps:/app
    command: >
      sh -c "
        pip install fastapi uvicorn jinja2 python-multipart &&
        python ui.py
      "
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - financial-network
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  financial-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16