global:
  smtp_smarthost: 'smtp:1025'
  smtp_from: 'alerts@financialplatform.local'
  smtp_require_tls: false

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'financial-team'
  routes:
    - match:
        severity: critical
      receiver: 'financial-team-urgent'
      repeat_interval: 1h
    - match:
        severity: high
      receiver: 'financial-team-high'
      repeat_interval: 2h
    - match:
        service: database
      receiver: 'database-team'
    - match:
        service: security
      receiver: 'security-team'
      repeat_interval: 1h

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

receivers:
  - name: 'financial-team'
    email_configs:
      - to: 'team@financialplatform.local'
        send_resolved: true
        headers:
          subject: 'Financial Platform Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Financial Platform Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p><small>Generated by Alertmanager at {{ .StartsAt }}</small></p>

  - name: 'financial-team-urgent'
    email_configs:
      - to: 'urgent@financialplatform.local'
        send_resolved: true
        headers:
          subject: '🚨 URGENT: Financial Platform Critical Alert'
        html: |
          <h2 style="color: red;">🚨 URGENT ALERT</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p><strong>IMMEDIATE ACTION REQUIRED</strong></p>
          <p><small>Generated by Alertmanager at {{ .StartsAt }}</small></p>

  - name: 'financial-team-high'
    email_configs:
      - to: 'high@financialplatform.local'
        send_resolved: true
        headers:
          subject: '⚠️ HIGH: Financial Platform Alert'
        html: |
          <h2 style="color: orange;">⚠️ HIGH PRIORITY ALERT</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p><small>Generated by Alertmanager at {{ .StartsAt }}</small></p>

  - name: 'database-team'
    email_configs:
      - to: 'database@financialplatform.local'
        send_resolved: true
        headers:
          subject: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>🗄️ Database Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p><small>Generated by Alertmanager at {{ .StartsAt }}</small></p>

  - name: 'security-team'
    email_configs:
      - to: 'security@financialplatform.local'
        send_resolved: true
        headers:
          subject: '🔒 Security Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>🔒 Security Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p><strong>SECURITY INVESTIGATION REQUIRED</strong></p>
          <p><small>Generated by Alertmanager at {{ .StartsAt }}</small></p>

templates:
  - '/etc/alertmanager/template/*.tmpl'

# Time intervals for different severity levels
time_intervals:
  - name: workdays
    time_intervals:
      - weekdays: ['monday:friday']
        times:
          - start_time: 09:00
            end_time: 17:00
        location: 'America/New_York'

  - name: weekends
    time_intervals:
      - weekdays: ['saturday', 'sunday']
        times:
          - start_time: 00:00
            end_time: 23:59

  - name: off_hours
    time_intervals:
      - weekdays: ['monday:friday']
        times:
          - start_time: 17:00
            end_time: 09:00
        location: 'America/New_York'
      - weekdays: ['saturday', 'sunday']
        times:
          - start_time: 00:00
            end_time: 23:59

# Route based on time
route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'financial-team'
  time_intervals:
    - name: workdays
      time_intervals:
        - weekdays: ['monday:friday']
          times:
            - start_time: 09:00
              end_time: 17:00
          location: 'America/New_York'
  routes:
    - match:
        severity: critical
      receiver: 'financial-team-urgent'
      repeat_interval: 1h
      time_intervals:
        - name: workdays
    - match:
        severity: high
      receiver: 'financial-team-high'
      repeat_interval: 2h
      time_intervals:
        - name: workdays
    - match:
        service: database
      receiver: 'database-team'
      time_intervals:
        - name: workdays
    - match:
        service: security
      receiver: 'security-team'
      repeat_interval: 1h
      time_intervals:
        - name: workdays