global:
  smtp_smarthost: 'smtp:1025'
  smtp_from: 'alerts@financialplatform.local'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    email_configs:
      - to: 'admin@financialplatform.local'
        subject: 'Financial Platform Alert: {{ .GroupLabels.alertname }}'
        body: 'Alert: {{ .GroupLabels.alertname }} - Status: {{ .Status }}'